#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if ynh_app_upgrading_from_version_before_or_equal_to 20251009~ynh1; then
	ynh_script_progression "Ensuring downward compatibility..."

	ynh_app_setting_set_default --key=phanpy_client_name --value="Phanpy"
	ynh_app_setting_set_default --key=phanpy_default_instance --value=""
	ynh_app_setting_set_default --key=phanpy_default_instance_registration_url --value=""
	ynh_app_setting_set_default --key=phanpy_privacy_policy_url --value="https://github.com/cheeaun/phanpy/blob/main/PRIVACY.MD"
	ynh_app_setting_set_default --key=phanpy_default_lang --value="en"
	ynh_app_setting_set_default --key=phanpy_referrer_policy --value="origin"
	ynh_app_setting_set_default --key=phanpy_translang_instances --value="translang.phanpy.social"
	ynh_app_setting_set_default --key=phanpy_img_alt_api_url --value=""
	ynh_app_setting_set_default --key=phanpy_giphy_api_key --value=""
	ynh_app_setting_set_default --key=phanpy_disallow_robots --value="true"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

mkdir "$install_dir/.build"
mv $install_dir/* "$install_dir/.build"
mv "$install_dir/.github" "$install_dir/.build"
ynh_safe_rm "$install_dir/.env"
mv "$install_dir/.gitattributes" "$install_dir/.build"
mv "$install_dir/.gitignore" "$install_dir/.build"
chown -R "$app:$app" "$install_dir/.build"

#=================================================
# APP ENV
#=================================================
ynh_script_progression "Adding $app's env file..."

ynh_config_add --template=".env" --destination="$install_dir/.build/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/.build
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

mv $install_dir/.build/dist/* $install_dir/
ynh_safe_rm "$install_dir/.build"
ynh_safe_rm "$install_dir/.npm"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
