#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=PHANPY_CLIENT_NAME --value="Phanpy"
ynh_app_setting_set_default --key=PHANPY_DEFAULT_INSTANCE --value=""
ynh_app_setting_set_default --key=PHANPY_DEFAULT_INSTANCE_REGISTRATION_URL --value=""
ynh_app_setting_set_default --key=PHANPY_PRIVACY_POLICY_URL --value="https://github.com/cheeaun/phanpy/blob/main/PRIVACY.MD"
ynh_app_setting_set_default --key=PHANPY_DEFAULT_LANG --value="en"
ynh_app_setting_set_default --key=PHANPY_REFERRER_POLICY --value="origin"
ynh_app_setting_set_default --key=PHANPY_TRANSLANG_INSTANCES --value="translang.phanpy.social"
ynh_app_setting_set_default --key=PHANPY_IMG_ALT_API_URL --value=""
ynh_app_setting_set_default --key=PHANPY_GIPHY_API_KEY --value=""
ynh_app_setting_set_default --key=PHANPY_DISALLOW_ROBOTS --value="true"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

mkdir "$install_dir/.build"
mv $install_dir/* "$install_dir/.build"
chown -R "$app:$app" "$install_dir/.build"

#=================================================
# APP ENV
#=================================================
ynh_script_progression "Adding $app's env file..."

ynh_config_add --template=".env" --destination="$install_dir/.build/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/.build
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

mv $install_dir/.build/dist/* $install_dir/
ynh_safe_rm "$install_dir/.build"
ynh_safe_rm "$install_dir/.npm"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"